WebNursePlanning/Controllers/AbsenceController.cs
using DomainModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repository.Interfaces;
using System;
using System.Threading.Tasks;
using WebNursePlanning.Models;

namespace WebNursePlanning.Controllers
{
	[Authorize(Roles = "ROLE_SUPER_ADMIN, ROLE_ADMIN")]
	public class AbsenceController : Controller
	{
		private readonly IAbsenceRepository _absenceRepository;
		private readonly IAppointmentRepository _appointmentRepository;
		private readonly INurseRepository _nurseRepository;
		private readonly IStatusRepository _statusRepository;
		private readonly UserManager<Person> _userManager;
		private readonly SignInManager<Person> _signInManager;

		public AbsenceController(IAbsenceRepository absenceRepository, IAppointmentRepository appointmentRepository, INurseRepository nurseRepository, IStatusRepository statusRepository, UserManager<Person> userManager, SignInManager<Person> signInManager)
		{
			_absenceRepository = absenceRepository;
			_appointmentRepository = appointmentRepository;
			_nurseRepository = nurseRepository;
			_statusRepository = statusRepository;
			_userManager = userManager;
			_signInManager = signInManager;
		}

		// GET: AbsenceController
		public async Task<IActionResult> Index()
		{
			var user = await _userManager.GetUserAsync(User);
			var listAbsences = await _absenceRepository.ListAbsenceById(user.Id);
			return View(listAbsences);
		}

		// GET: AbsenceController/Details/5
		public async Task<IActionResult> Details(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var absence = await _absenceRepository.Details(id);
			if (absence == null)
			{
				return NotFound();
			}

			return View(absence);
		}

		// GET: AbsenceController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: AbsenceController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(AbsenceViewModel absence)
		{
			if (ModelState.IsValid)
			{
				var dateStart = new DateTime(absence.DateStart.Year,
											absence.DateStart.Month,
											absence.DateStart.Day,
											absence.TimeStart.Hour,
											absence.TimeStart.Minute,
											absence.TimeStart.Second);

				var dateEnd = new DateTime(absence.DateEnd.Year,
											absence.DateEnd.Month,
											absence.DateEnd.Day,
											absence.TimeEnd.Hour,
											absence.TimeEnd.Minute,
											absence.TimeEnd.Second);
				var a = new Absence()
				{
					DateEnd = dateEnd,
					DateStart = dateStart,
					Reason = absence.Motif,
					NurseId = absence.NurseId
				};
				await _absenceRepository.Create(a);

				return RedirectToAction(nameof(Index));
			}

			return RedirectToAction("Index");
		}

		// GET: AbsenceController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: AbsenceController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(Guid id, [Bind("Id,DateStart,DateEnd,Motif,NurseId")] Absence absence)
		{
			if (id != absence.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					await _absenceRepository.Edit(absence);
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!AbsenceExist(absence.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}

			return View(absence);
		}

		// GET: AbsenceController/Delete/5
		public async Task<IActionResult> Delete(Guid? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var absence = await _absenceRepository.Details(id);
			if (absence == null)
			{
				return NotFound();
			}

			return View(absence);
		}

		// POST: AbsenceController/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(Guid id)
		{
			await _absenceRepository.Delete(id);
			return RedirectToAction(nameof(Index));
		}

		private bool AbsenceExist(Guid id)
		{
			return _absenceRepository.Exists(id);
		}
	}
}

WebNursePlanning/Controllers/NurseController.cs
using DomainModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebApiNursePlanning.Controllers
{
    [Authorize(Roles = "ROLE_SUPER_ADMIN")]
    public class NurseController : Controller
    {
        private readonly ILogger<NurseController> logger;
        private readonly UserManager<Person> userManager;
        private readonly SignInManager<Person> signInManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public NurseController(ILogger<NurseController> logger,
            UserManager<Person> userManager,
            RoleManager<IdentityRole> roleManager,
            SignInManager<Person> signInManager)
        {
            this.logger = logger;
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.signInManager = signInManager;
        }

        // GET: NurseController
        public async Task<ActionResult> IndexAsync()
        {
            var people = await userManager.GetUsersInRoleAsync("ROLE_ADMIN");
            var nurses = new List<Nurse>();
            foreach (var item in people)
                nurses.Add(item as Nurse);

            return View(nurses);
        }

        // GET: NurseController/Details/5
        public async Task<ActionResult> DetailsAsync(string id)
        {
            if (id is null)
            {
                return BadRequest();
            }

            var nurse = await userManager.FindByIdAsync(id) as Nurse;
            if (nurse is null)
            {
                return NotFound();
            }

            return View(nurse);
        }
    }
}

WebNursePlanning/Controllers/PatientController.cs
using DomainModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebPatientPlanning.Controllers
{
    [Authorize(Roles = "ROLE_SUPER_ADMIN, ROLE_ADMIN")]
    public class PatientController : Controller
    {
        private readonly ILogger<PatientController> logger;
        private readonly UserManager<Person> userManager;
        private readonly SignInManager<Person> signInManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public PatientController(ILogger<PatientController> logger,
            UserManager<Person> userManager,
            RoleManager<IdentityRole> roleManager,
            SignInManager<Person> signInManager)
        {
            this.logger = logger;
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.signInManager = signInManager;
        }

        // GET: PatientController
        public async Task<ActionResult> IndexAsync()
        {
            var people = await userManager.GetUsersInRoleAsync("ROLE_USER");
            var patients = new List<Patient>();
            foreach (var item in people)
                patients.Add(item as Patient);

            return View(patients);
        }

        // GET: PatientController/Details/5
        public async Task<ActionResult> DetailsAsync(string id)
        {
            if (id is null)
            {
                return BadRequest();
            }

            var patient =  await userManager.FindByIdAsync(id) as Patient;
            if (patient is null)
            {
                return NotFound();
            }

            return View(patient);
        }
    }
}

WebNursePlanning/Controllers/SuperAdminController.cs
using DomainModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using WebApiNursePlanning.Controllers;
using WebPatientPlanning.Controllers;

namespace WebNursePlanning.Controllers
{
    [Authorize(Roles = "ROLE_SUPER_ADMIN")]
    public class SuperAdminController : Controller
    {
        private readonly ILogger<HomeController> logger;
        private readonly UserManager<Person> userManager;
        private readonly SignInManager<Person> signInManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public SuperAdminController(ILogger<HomeController> logger,
            UserManager<Person> userManager,
            RoleManager<IdentityRole> roleManager,
            SignInManager<Person> signInManager)
        {
            this.logger = logger;
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.signInManager = signInManager;
        }
        // GET: SuperAdminController
        public async Task<ActionResult> Index()
        {
            var listPatient = await userManager.GetUsersInRoleAsync("ROLE_USER");
            var listNurse = await userManager.GetUsersInRoleAsync("ROLE_ADMIN");

            return View(listNurse);
        }

        // GET: SuperAdminController/ActivateNurse/5
        public async Task<ActionResult> ActivateNurseAsync(string id)
        {
            var person = await userManager.FindByIdAsync(id);

            if (person is null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: SuperAdminController/ActivateNurse/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ActivateNurseAsync(string Id, bool isActive)
        {
            var person = await userManager.FindByIdAsync(Id);
            person.IsActive = !isActive;
            var checkNurse = await userManager.UpdateAsync(person);
            if (person.GetType() == typeof(Nurse))
                return RedirectToAction(nameof(Index), "Nurse");

            return RedirectToAction(nameof(Index), "Patient");
        }
    }
}

WebNursePlanning/Views/Shared/_DetailsNurse.cshtml
@model DomainModel.Nurse

<div>
     <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayName("Nom")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Prénom")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Date de Naissance")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Adresse")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("N° sécurité sociale")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SiretNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("E-mail")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Téléphone")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>

<div>
    <a asp-area="" asp-controller="Nurse" asp-action="Index">Retour à la liste des infirmier(e)s</a>
</div>

WebNursePlanning/Views/Shared/_DetailsPatient.cshtml
@model DomainModel.Patient

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayName("Nom")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Prénom")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Date de naissance")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Adresse")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("N° sécurité sociale")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SocialSecurityNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("E-mail")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Téléphone")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="" asp-controller="Patient" asp-action="Index">Retour à la gestion des comptes</a>
</div>

WebNursePlanning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PrenezMoiViteSvp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/png" href="/css/logo.png" sizes="16x16">
</head>
<body style="background-image:url(/css/background.jpg); background-size:cover">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color: #e8f1e3;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/css/logo.png" width="140" height="120"></a>

                @*<a asp-action="Index">
                    <img src="/css/logo.png" width="140" height="120">
                </a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        @if ((User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_USER")))
                        {//Si l'utilisateur connecté est infirmier(role admin)
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Rendez-vous</a>
                            </li>
                        }
                        @if (User.IsInRole("ROLE_ADMIN"))
                        {//Si l'utilisateur connecté est infirmier(role admin)
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Absence" asp-action="Index">Absences</a>
                            </li>
                        }
                        @if (User.IsInRole("ROLE_SUPER_ADMIN"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SuperAdmin" asp-action="Index">Gestion des comptes</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted" style="background-color: #e8f1e3;">
        <div class="container">
            &copy; 2021 - PrenezMoiViteSvp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Confidentialité</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebNursePlanning/Views/Shared/_ListAppointments.cshtml
@model IEnumerable<DomainModel.Appointment>

@{
    ViewData["Title"] = "Liste des Rendez-vous";
}

<h1>Liste de vos Rendez-vous</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Date)*@
                Date
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.AtHome)*@
                A Domicile
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Nurse)*@
                Infirmier(e)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Patient)*@
                Patient(e)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AtHome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nurse.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Patient.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Modification</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Détails</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Supprimer</a>
            </td>
        </tr>
}
    </tbody>
</table>