WebNursePlanning/Models/AppointmentViewModel.cs
using DomainModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebNursePlanning.Models
{
	public class AppointmentViewModel
	{
		[Required]
		[DataType(DataType.Date)]
		[Display(Name = "Date du rendez-vous")]
		public DateTime Date { get; set; }

		[Required]
		[DataType(DataType.Time)]
		public DateTime Time { get; set; }

		[Required]
		[Display(Name = "A domicile")]
		public bool AtHome { get; set; }

		[Required]
		[Display(Name = "Infirmier(e)")]
		public string NurseId { get; set; }

		[Required(ErrorMessage = "ups")]
		[Display(Name = "Patient(e)")]
		public string PatientId { get; set; }

		[Required]
		[Display(Name = "Motif du rendez-vous")]
		public string Reason { get; set; }

		public Guid StatusId { get; set; }

		public ICollection<Message> Messages { get; set; }
	}
}

WebNursePlanning/Controllers/AppointmentsController.cs
using DomainModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Repository.Interfaces;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using WebNursePlanning.Models;
using WebNursePlanning.Shared.Components;

namespace WebNursePlanning.Controllers
{
    [Authorize(Roles = "ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER")]
    public class AppointmentsController : Controller
    {
        private readonly IAppointmentRepository _appointmentRepository;
        private readonly INurseRepository _nurseRepository;
        private readonly IPatientRepository _patientRepository;
        private readonly IStatusRepository _statusRepository;
        private readonly UserManager<Person> _userManager;
        private readonly SignInManager<Person> _signInManager;

        public AppointmentsController(IAppointmentRepository appointmentRepository,
                                        INurseRepository nurseRepository,
                                        IPatientRepository patientRepository,
                                        IStatusRepository statusRepository,
                                        UserManager<Person> userManager,
                                        SignInManager<Person> signInManager)
        {
            _appointmentRepository = appointmentRepository;
            _nurseRepository = nurseRepository;
            _patientRepository = patientRepository;
            _statusRepository = statusRepository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: Appointments
        public async Task<IActionResult> Index(string id = null)
        {
            var user = await _userManager.GetUserAsync(User);
            var listAppointments = await _appointmentRepository.ListAppointmentsById(id is null ? user.Id : id);
            return View(listAppointments);
        }



        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _appointmentRepository.Details(id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }
        // GET: Appointments/Create
        public async Task<IActionResult> Create()
        {
            //ViewData["StatusId"] = await _statusRepository.GetStatusId("En cours de validation");
            var liste = await _statusRepository.ListStatuses();
            ViewData["StatusId"] = liste.FirstOrDefault(s => s.Name == "En attente").Id;

            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Appointment appointment)
        {
            if (ModelState.IsValid)
            {

                //appointment.Id = Guid.NewGuid();
                await _appointmentRepository.Create(appointment);

                return RedirectToAction(nameof(Index));
            }
            return View(appointment);
        }

        public IActionResult GenerateCalendar(string personId, int decalage)
        {
            return ViewComponent("CreateAppointmentCalendar", new { id = personId, decalage });
        }
        public async Task<IActionResult> Transfer(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var appointments = await _appointmentRepository.ListAppointments();
            var appointment = await _appointmentRepository.Details(id);
            //var list = _nurseRepository.ListNursesWithAppointment();
            //var dateOfWeek = appointment.Date;
            //var c = _appointmentRepository.CheckAvailabilityAppointment(appointments, dateOfWeek);
            if (appointment == null)
            {
                return NotFound();
            }

            var listNurses = await _nurseRepository.ListNurses();
            var dicoNurses = listNurses.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["NurseId"] = new SelectList(dicoNurses, "Key", "Value", appointment.NurseId);
            //ViewData["NurseId"] = new SelectList(await _nurseRepository.ListNurses(), "Id", "Id", appointment.NurseId);

            var listPatients = await _patientRepository.ListPatients();
            var dicoPatients = listPatients.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["PatientId"] = new SelectList(dicoPatients, "Key", "Value", appointment.PatientId);
            //ViewData["PatientId"] = new SelectList(await _patientRepository.ListPatients(), "Id", "Id", appointment.PatientId);
            ViewData["StatusId"] = new SelectList(await _statusRepository.ListStatuses(), "Id", "Name", appointment.StatusId);

            return View(appointment);
        }

        // POST: Appointments/Transfer
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Transfer(Guid id, [Bind("Id,Date,Reason,AtHome,NurseId,PatientId,StatusId")] Appointment appointment)
        {

            if (id != appointment.Id)
            {
                return NotFound();
            }

            var listAppointments = await _appointmentRepository.ListAppointmentsById(appointment.NurseId);
            var dateOfWeek = appointment.Date;
            var isAvailable = _appointmentRepository.CheckAvailabilityAppointment(listAppointments, dateOfWeek);

            if (ModelState.IsValid)
            {
                try
                {
                    if (isAvailable)
                        await _appointmentRepository.Edit(appointment);
                    else if (isAvailable == false)
                    {
                        //ViewBag["Message"]= "L'infirmier est occupé";
                        return Content("<script language='javascript' type='text/javascript'>alert('L'infirmier est occupé');</script>");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }



            var listNurses = await _nurseRepository.ListNurses();
            var dicoNurses = listNurses.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["NurseId"] = new SelectList(dicoNurses, "Key", "Value", appointment.NurseId);
            //ViewData["NurseId"] = new SelectList(await _nurseRepository.ListNurses(), "Id", "Id", appointment.NurseId);

            var listPatients = await _patientRepository.ListPatients();
            var dicoPatients = listPatients.ToDictionary(b => b.Id, b => b.LastName + " " + b.FirstName);
            ViewData["PatientId"] = new SelectList(dicoPatients, "Key", "Value", appointment.PatientId);
            //ViewData["PatientId"] = new SelectList(await _patientRepository.ListPatients(), "Id", "Id", appointment.PatientId);
            ViewData["StatusId"] = new SelectList(await _statusRepository.ListStatuses(), "Id", "Name", appointment.StatusId);

            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _appointmentRepository.Details(id);
            if (appointment == null)
            {
                return NotFound();
            }


            ViewData["StatusId"] = new SelectList(await _statusRepository.ListStatuses(), "Id", "Name", appointment.StatusId);

            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Date,Reason,AtHome,NurseId,PatientId,StatusId")] Appointment appointment)
        {
            if (id != appointment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var oldAppointment = _appointmentRepository.Details(id).GetAwaiter().GetResult();

                    if (oldAppointment.Reason != appointment.Reason ||
                        oldAppointment.Date != appointment.Date ||
                        oldAppointment.NurseId != appointment.NurseId)
                    {
                                          oldAppointment.StatusId = await _statusRepository.GetStatusId("En attente");
                    }
                    else
                    {
                        oldAppointment.StatusId = appointment.StatusId;
                    }

                    oldAppointment.Reason = appointment.Reason;
                    oldAppointment.Date = appointment.Date;
                    oldAppointment.NurseId = appointment.NurseId;

WebNursePlanning/Views/Appointments/Components/CreateAppointmentCalendarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebNursePlanning.Shared.Components
{
    public class CreateAppointmentCalendarViewComponent : ViewComponent
    {
        private readonly IAppointmentRepository _appointmentRepository;
        public CreateAppointmentCalendarViewComponent(IAppointmentRepository appointmentRepository)
        {
            _appointmentRepository = appointmentRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(string id, int decalage =0)
        {

            Dictionary<string, List<TimeSpan>> dico = await _appointmentRepository.GetListAvailableAppointments(id,decalage:decalage);

            ViewData["AppointmentsAvailables"] = dico;
            return View();
        }
       
    }
}

WebNursePlanning/Views/Appointments/Components/EditAppointmentCalendarViewComponent.cs
using DomainModel;
using Microsoft.AspNetCore.Mvc;
using Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebNursePlanning.Shared.Components
{
    public class EditAppointmentCalendarViewComponent : ViewComponent
    {
        private readonly IAppointmentRepository _appointmentRepository;
        public EditAppointmentCalendarViewComponent(IAppointmentRepository appointmentRepository)
        {
            _appointmentRepository = appointmentRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(string personId, List<Appointment> appToEdit)
        {

            Dictionary<string, List<TimeSpan>> dico = await _appointmentRepository.GetListAvailableAppointments(personId, appToEdit);

            ViewData["AppointmentsAvailables"] = dico;
            return View();
        }
       
    }
}

WebNursePlanning/Views/Appointments/Create.cshtml
@model DomainModel.Appointment
@using Microsoft.AspNetCore.Identity
@inject SignInManager<DomainModel.Person> SignInManager
@inject UserManager<DomainModel.Person> UserManager
@inject WebNursePlanning.Services.AppointmentsService MyAppointment
@addTagHelper *,WebNursePlanning

@{
    ViewData["Title"] = "Create";

}

<h1>Prise de Rendez-vous</h1>
<hr />
<div class="row">

    <input type="button" id="Previous" name="Previous" value="Semaine Precedent" />
    <input type="button" id="Next" name="Next" value="Semaine Suivant" />
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div id="Calendar" class="form-group">
            @await Component.InvokeAsync("CreateAppointmentCalendar", new { id = UserManager.GetUserId(User) })
        </div>

        <div class="form-group">
            <label asp-for="Reason" class="control-label"></label>
            <input asp-for="Reason" class="form-control" />
            <span asp-validation-for="Reason" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="AtHome" />@Html.DisplayNameFor(model => model.AtHome)
            </label>
        </div>
        @if (User.IsInRole("ROLE_ADMIN"))
        {//Si l'utilisateur connecté est infirmier(role admin)
            <div class="form-group">
                <input asp-for="NurseId" style="display:none;" value="@UserManager.GetUserId(User)" />
            </div>
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <select asp-for="PatientId" class="form-control"
                        asp-items="MyAppointment.GetSelectListPatientsAsync().GetAwaiter().GetResult()">
                </select>
            </div>
            @*<div hidden id="Nurse">@UserManager.GetUserId(User)</div>*@
        }
        else if (User.IsInRole("ROLE_USER"))
        {//Si l'utilisateur est un patient (role user)
            <div class="form-group">
                <label asp-for="NurseId" class="control-label"></label>
                <select asp-for="NurseId" class="form-control"
                        asp-items="MyAppointment.GetSelectListNursesAsync().GetAwaiter().GetResult()">
                </select>
            </div>
            <div class="form-group">
                <input asp-for="PatientId" style="display:none;" value="@UserManager.GetUserId(User)" />
            </div>
        }

        <div class="form-group">
            <input asp-for="StatusId" style="display:none;" value="@ViewBag.StatusId" />
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Retour à la liste de vos rendez-vous</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        var user = $("#NurseId").val();
        var decalage = 0;
        $(function () {
            $("#Next").click(function (e) {
                e.preventDefault();
                decalage++;
                $.get('/Appointments/GenerateCalendar', {
                    personId: user,
                    decalage: decalage
                }
                    , function (data) { // data => PartialView
                        $('#Calendar').html(data);
                    });
            });
        });
        $(function () {
            $("#Previous").click(function (e) {
                e.preventDefault();
                if (decalage > 0) {
                    decalage--;
                    $.get('/Appointments/GenerateCalendar', {
                        personId: user,
                        decalage: decalage
                    }
                        , function (data) { // data => PartialView
                            $('#Calendar').html(data);
                        });
                }
            });
        });
        $(function () {
            $('#NurseId').on('change', function (e) {
                 user = $('#NurseId option:selected').val();
                e.preventDefault();
                $.get('/Appointments/GenerateCalendar', {
                    personId: user,
                    decalage: decalage
                }
                    , function (data) { // data => PartialView
                        $('#Calendar').html(data);
                    });
            });    
        });
    </script>

}

WebNursePlanning/Views/Appointments/Delete.cshtml
@model DomainModel.Appointment

@{
    ViewData["Title"] = "Delete";
}

<h1>Suppression de RDV</h1>

<h3>Etes vous sur de vouloir annuler ceci?</h3>
<div>
    <hr />
    <h4>Rendez-vous</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("À domicile")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AtHome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NurseId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nurse.LastName)
            @Html.DisplayFor(model => model.Nurse.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.LastName)
            @Html.DisplayFor(model => model.Patient.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Suppimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

WebNursePlanning/Views/Appointments/Details.cshtml
@model DomainModel.Appointment

@{
    ViewData["Title"] = "Details";
}

<h1>Détails</h1>

<div>
    <h4>Rendez-Vous</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("À domicile")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AtHome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NurseId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nurse.LastName)
            @Html.DisplayFor(model => model.Nurse.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.LastName)
            @Html.DisplayFor(model => model.Patient.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Modifier</a> |
    <a asp-action="Index">Retour à la liste</a>
</div>

WebNursePlanning/Views/Appointments/Edit.cshtml
@model DomainModel.Appointment
@using Microsoft.AspNetCore.Identity
@inject SignInManager<DomainModel.Person> SignInManager
@inject UserManager<DomainModel.Person> UserManager
@inject WebNursePlanning.Services.AppointmentsService MyAppointment

@{
    ViewData["Title"] = "Modification Rendez-vous";
}

<h1>Modification de votre rendez-vous</h1>

<hr />
<div class="row">
    <input type="button" id="Previous" name="Previous" value="Semaine Precedent" />
    <input type="button" id="Next" name="Next" value="Semaine Suivant" />
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Reason" class="control-label"></label>
            <input asp-for="Reason" class="form-control" />
            <span asp-validation-for="Reason" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="AtHome" /> @Html.DisplayName("A domicile")
            </label>
        </div>
        @if (User.IsInRole("ROLE_ADMIN"))
        {//Si le l'utilisateur connecté est infirmier(role admin)
            <div class="form-group">
                <input asp-for="NurseId" class="form-control" style="display:none;" value="@UserManager.GetUserId(User)" />
            </div>
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <select asp-for="PatientId" class="form-control"
                        asp-items="MyAppointment.GetSelectListPatientsAsync(Model.PatientId).GetAwaiter().GetResult()"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Statut</label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
        }
        else if (User.IsInRole("ROLE_USER"))
        {//Si l'utilisateur est un patient (role user)
            <input asp-for="StatusId" hidden />
            <div class="form-group">
                <label asp-for="NurseId" class="control-label"></label>
                <select asp-for="NurseId" class="form-control"
                        asp-items="MyAppointment.GetSelectListNursesAsync(Model.NurseId).GetAwaiter().GetResult()"></select>
            </div>
            <div class="form-group">
                <input asp-for="PatientId" class="form-control" style="display:none;" value="@UserManager.GetUserId(User)" />
            </div>
        }

        <div id="Calendar" class="form-group">
            @await Component.InvokeAsync("EditAppointmentCalendar", new { personId = UserManager.GetUserId(User), appToEdit = new List<DomainModel.Appointment> { Model } })
        </div>
        <div class="form-group">
            <input type="submit" value="Sauvegarder" class="btn btn-primary" />
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        var user = $("#NurseId").val();
        var decalage = 0;
        $(function () {
            $("#Next").click(function (e) {
                e.preventDefault();
                decalage++;
                $.get('/Appointments/GenerateCalendar', {
                    personId: user,
                    decalage: decalage
                }
                    , function (data) { // data => PartialView
                        $('#Calendar').html(data);
                    });
            });
        });
        $(function () {
            $("#Previous").click(function (e) {
                e.preventDefault();
                if (decalage > 0) {
                    decalage--;
                    $.get('/Appointments/GenerateCalendar', {
                        personId: user,
                        decalage: decalage
                    }
                        , function (data) { // data => PartialView
                            $('#Calendar').html(data);
                        });
                }
            });
        });
        $(function () {
            $('#NurseId').on('change', function (e) {
                user = $('#NurseId option:selected').val();
                e.preventDefault();
                $.get('/Appointments/GenerateCalendar', {
                    personId: user,
                    decalage: decalage
                }
                    , function (data) { // data => PartialView
                        $('#Calendar').html(data);
                    });
            });
        });
    </script>
}

WebNursePlanning/Views/Appointments/Index.cshtml
@model IEnumerable<DomainModel.Appointment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Nouveau Rdv</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AtHome)
            </th>
            @if (User.IsInRole("ROLE_USER"))
            {//Si l'utilisateur connecté est patient(role user)
                <th>
                    @Html.DisplayNameFor(model => model.NurseId)
                </th>
            }
            else if (User.IsInRole("ROLE_ADMIN"))
            {//Si l'utilisateur est un infirmier (role admin)
                <th>
                    @Html.DisplayNameFor(model => model.PatientId)
                </th>
            }
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AtHome)
                </td>
                @if (User.IsInRole("ROLE_USER"))
                {//Si l'utilisateur connecté est patient(role user)
                    <td>
                        @Html.DisplayFor(modelItem => item.Nurse.LastName)
                        @Html.DisplayFor(modelItem => item.Nurse.FirstName)
                    </td>
                }
                else if (User.IsInRole("ROLE_ADMIN"))
                {//Si l'utilisateur est un infirmier (role admin)
                    <td>
                        @Html.DisplayFor(modelItem => item.Patient.LastName)
                        @Html.DisplayFor(modelItem => item.Patient.FirstName)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Status.Name)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Détails</a>

                    @if (item.Status.Name != "Annulé" && item.Status.Name != "Fermé" && item.Status.Name != "Rejeté")
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Modifier</a> <span>  </span>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Supprimer</a>
                    }
                    else
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary disabled">Modifier</a> <span>  </span>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-secondary disabled">Supprimer</a>
                    }
                    @if (User.IsInRole("ROLE_ADMIN") || User.IsInRole("ROLE_SUPER_ADMIN"))
                    {
                        <a asp-action="Transfer" asp-route-id="@item.Id">Transfert</a>
                        <a asp-action="RejectStatus" asp-route-id="@item.Id">Rejeter</a>
                        <a asp-action="ValidateStatus" asp-route-id="@item.Id">Valider</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

WebNursePlanning/Views/Appointments/RejectStatus.cshtml
@model DomainModel.Appointment

@{
    ViewData["Title"] = "RejectStatus";
}

<h1>Rejet du RDV</h1>

<h3>Etes vous sur de vouloir rejeter ceci?</h3>
<div>
    <hr />
    <h4>Rendez-vous</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AtHome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AtHome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NurseId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nurse.LastName)
            @Html.DisplayFor(model => model.Nurse.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.LastName)
            @Html.DisplayFor(model => model.Patient.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
    </dl>

    <form asp-action="RejectStatus">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Valider" class="btn btn-dark" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>